import { categoryNames } from '@/lib/categories'
import {
  filterStorefrontProducts,
  isStorefrontProductVisible,
} from '@/lib/payment-test-mode'

export type Product = {
  slug: string
  name: string
  price: number
  originalPrice?: number
  image: string
  images: string[]
  category: string
  collections: string[]
  fabric: string
  weave: string
  length: string
  blouse: string
  care: string
  availability: 'In Stock' | 'Low Stock' | 'Made to Order'
  isNew?: boolean
  /** ISO timestamp — from DB when available; used for New Arrivals newest-first ordering. */
  createdAt?: string
  description: string
}

export const products: Product[] = [
  {
    slug: 'handwoven-silk-saree',
    name: 'Handwoven Silk Saree',
    price: 12999,
    originalPrice: 15999,
    image: 'https://res.cloudinary.com/tcjtyr02/image/upload/v1787740183/10.png',
    images: ['https://res.cloudinary.com/tcjtyr02/image/upload/v1787740183/10.png'],
    category: 'Silk',
    collections: ['silk-sarees', 'new-arrivals'],
    fabric: 'Pure Mulberry Silk',
    weave: 'Handwoven',
    length: '5.5 metres + 0.8 m blouse',
    blouse: 'Unstitched blouse piece included',
    care: 'Dry clean only. Store wrapped in muslin cloth.',
    availability: 'In Stock',
    isNew: true,
    description:
      'A luminous handwoven silk saree with a fine gold zari border, crafted on traditional pit looms. Its fluid drape and understated sheen make it a timeless addition to any wardrobe.',
  },
  {
    slug: 'banarasi-heritage-saree',
    name: 'Banarasi Heritage Saree',
    price: 22499,
    originalPrice: 26999,
    image: 'https://res.cloudinary.com/tcjtyr02/image/upload/v1787740183/9.png',
    images: ['https://res.cloudinary.com/tcjtyr02/image/upload/v1787740183/9.png'],
    category: 'Banarasi',
    collections: ['banarasi-sarees', 'wedding-collection'],
    fabric: 'Katan Silk',
    weave: 'Handwoven Banarasi Brocade',
    length: '5.5 metres + 0.8 m blouse',
    blouse: 'Matching brocade blouse piece included',
    care: 'Dry clean only. Avoid direct sunlight.',
    availability: 'Low Stock',
    isNew: true,
    description:
      'An opulent Banarasi saree woven with intricate all-over gold brocade zari. Each piece takes weeks to weave, carrying the legacy of Varanasi master craftsmen.',
  },
  {
    slug: 'elegant-kanjeevaram-saree',
    name: 'Elegant Kanjeevaram Saree',
    price: 18999,
    originalPrice: 21999,
    image: 'https://res.cloudinary.com/tcjtyr02/image/upload/v1787740182/6.png',
    images: ['https://res.cloudinary.com/tcjtyr02/image/upload/v1787740182/6.png'],
    category: 'Silk',
    collections: ['silk-sarees', 'wedding-collection', 'festive-collection'],
    fabric: 'Pure Kanjeevaram Silk',
    weave: 'Handwoven with contrast border',
    length: '6.0 metres + 0.8 m blouse',
    blouse: 'Contrast blouse piece included',
    care: 'Dry clean only. Store flat, refold periodically.',
    availability: 'In Stock',
    description:
      'A regal Kanjeevaram saree with a lustrous mustard-gold body and a deep maroon temple border. A South Indian classic reserved for the most cherished occasions.',
  },
  {
    slug: 'soft-cotton-handloom-saree',
    name: 'Soft Cotton Handloom Saree',
    price: 5499,
    originalPrice: 6999,
    image: 'https://res.cloudinary.com/tcjtyr02/image/upload/v1787740182/4.png',
    images: ['https://res.cloudinary.com/tcjtyr02/image/upload/v1787740182/4.png'],
    category: 'Cotton',
    collections: ['cotton-handloom', 'new-arrivals'],
    fabric: 'Handspun Cotton',
    weave: 'Handloom',
    length: '5.5 metres + 0.8 m blouse',
    blouse: 'Unstitched blouse piece included',
    care: 'Gentle hand wash in cold water. Line dry in shade.',
    availability: 'In Stock',
    isNew: true,
    description:
      'A breathable handspun cotton saree in natural undyed tones with a subtle woven border. Effortless everyday elegance for the modern woman.',
  },
  {
    slug: 'traditional-chanderi-saree',
    name: 'Traditional Chanderi Saree',
    price: 7999,
    image: 'https://res.cloudinary.com/tcjtyr02/image/upload/v1787740181/5.png',
    images: ['https://res.cloudinary.com/tcjtyr02/image/upload/v1787740181/5.png'],
    category: 'Chanderi',
    collections: ['cotton-handloom', 'festive-collection'],
    fabric: 'Chanderi Silk-Cotton',
    weave: 'Handwoven with buti motifs',
    length: '5.5 metres + 0.8 m blouse',
    blouse: 'Unstitched blouse piece included',
    care: 'Dry clean recommended.',
    availability: 'Made to Order',
    description:
      'A feather-light Chanderi saree in soft blush pink, scattered with delicate gold buti motifs. Sheer, graceful and beautifully translucent.',
  },
  {
    slug: 'festive-silk-collection-saree',
    name: 'Festive Silk Collection Saree',
    price: 16499,
    originalPrice: 19999,
    image: 'https://res.cloudinary.com/tcjtyr02/image/upload/v1787740181/3.png',
    images: ['https://res.cloudinary.com/tcjtyr02/image/upload/v1787740181/3.png'],
    category: 'Silk',
    collections: ['silk-sarees', 'festive-collection', 'new-arrivals'],
    fabric: 'Pure Silk',
    weave: 'Handwoven with zari pallu',
    length: '5.5 metres + 0.8 m blouse',
    blouse: 'Matching blouse piece included',
    care: 'Dry clean only.',
    availability: 'In Stock',
    isNew: true,
    description:
      'A celebratory emerald silk saree with an opulent gold zari pallu. Rich, radiant and made for festivities and milestone moments.',
  },
  {
    slug: 'product-7',
    name: 'Product 7 — Details Coming Soon',
    // PLACEHOLDER: replace with real price (do not use as sale price)
    price: 0,
    image: 'https://res.cloudinary.com/tcjtyr02/image/upload/v1787740181/8.png',
    images: ['https://res.cloudinary.com/tcjtyr02/image/upload/v1787740181/8.png'],
    category: 'Saree',
    collections: ['new-arrivals'],
    fabric: 'PLACEHOLDER',
    weave: 'PLACEHOLDER',
    length: 'PLACEHOLDER',
    blouse: 'PLACEHOLDER',
    care: 'PLACEHOLDER',
    availability: 'In Stock',
    isNew: true,
    description: 'PLACEHOLDER — product details coming soon.',
  },
  {
    slug: 'product-8',
    name: 'Product 8 — Details Coming Soon',
    // PLACEHOLDER: replace with real price (do not use as sale price)
    price: 0,
    image: 'https://res.cloudinary.com/tcjtyr02/image/upload/v1787740181/2.png',
    images: ['https://res.cloudinary.com/tcjtyr02/image/upload/v1787740181/2.png'],
    category: 'Saree',
    collections: ['new-arrivals'],
    fabric: 'PLACEHOLDER',
    weave: 'PLACEHOLDER',
    length: 'PLACEHOLDER',
    blouse: 'PLACEHOLDER',
    care: 'PLACEHOLDER',
    availability: 'In Stock',
    isNew: true,
    description: 'PLACEHOLDER — product details coming soon.',
  },
  {
    slug: 'masterpiece-embroidery-pure-cotton-kota-handloom-saree',
    name: 'Masterpiece Embroidery Pure Cotton Kota Handloom Saree',
    price: 4700,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916349/WhatsApp_Image_2026-08-28_at_4.03.22_PM.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916349/WhatsApp_Image_2026-08-28_at_4.03.22_PM.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916348/WhatsApp_Image_2026-08-28_at_4.03.21_PM.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916348/WhatsApp_Image_2026-08-28_at_4.03.21_PM_2.jpg',
    ],
    category: 'Kota',
    collections: ['kota-collection'],
    fabric: '—',
    weave: '—',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'With Blouse. Free Shipping.',
  },
  {
    slug: 'masterpiece-embroidery-kota-handloom-saree-sky-blue-floral',
    name: 'Masterpiece Embroidery Pure Cotton Kota Handloom Saree — Sky Blue Floral',
    price: 4700,
    originalPrice: 5400,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916347/WhatsApp_Image_2026-08-28_at_4.03.21_PM_1.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916347/WhatsApp_Image_2026-08-28_at_4.03.21_PM_1.jpg',
    ],
    category: 'Kota Handloom',
    collections: ['kota-collection', 'new-arrivals'],
    fabric: 'Pure Cotton Kota Handloom',
    weave: '—',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    isNew: true,
    description:
      'Masterpiece embroidery pure cotton Kota handloom saree featuring elegant floral embroidery and a lightweight breathable weave. Perfect for festive occasions, office wear, and elegant everyday styling.',
  },
  {
    slug: 'masterpiece-embroidery-kota-handloom-saree-beige-floral',
    name: 'Masterpiece Embroidery Pure Cotton Kota Handloom Saree — Beige Floral',
    price: 4700,
    originalPrice: 5400,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916347/WhatsApp_Image_2026-08-28_at_4.03.20_PM.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916347/WhatsApp_Image_2026-08-28_at_4.03.20_PM.jpg',
    ],
    category: 'Kota Handloom',
    collections: ['kota-collection', 'new-arrivals'],
    fabric: 'Pure Cotton Kota Handloom',
    weave: '—',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    isNew: true,
    description:
      'Elegant beige Kota handloom saree with intricate embroidery, soft cotton texture, and timeless handcrafted detailing.',
  },
  {
    slug: 'masterpiece-embroidery-kota-handloom-saree-lavender-floral',
    name: 'Masterpiece Embroidery Pure Cotton Kota Handloom Saree — Lavender Floral',
    price: 4700,
    originalPrice: 5400,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916347/WhatsApp_Image_2026-08-28_at_4.03.20_PM_2.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916347/WhatsApp_Image_2026-08-28_at_4.03.20_PM_2.jpg',
    ],
    category: 'Kota Handloom',
    collections: ['kota-collection', 'new-arrivals'],
    fabric: 'Pure Cotton Kota Handloom',
    weave: '—',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    isNew: true,
    description:
      'Soft lavender pure cotton Kota handloom saree with premium floral embroidery and lightweight festive drape.',
  },
  {
    slug: 'kota-handloom-saree-new-collection-01',
    name: 'Kota Handloom Saree — New Collection 01',
    price: 4700,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916346/WhatsApp_Image_2026-08-28_at_4.03.20_PM_1.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916346/WhatsApp_Image_2026-08-28_at_4.03.20_PM_1.jpg',
    ],
    category: 'Kota Handloom',
    collections: ['kota-collection'],
    fabric: '—',
    weave: '—',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    isNew: true,
    description: 'With Blouse. Free Shipping.',
  },
  {
    slug: 'kota-handloom-saree-new-collection-02',
    name: 'Kota Handloom Saree — New Collection 02',
    price: 4700,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916346/WhatsApp_Image_2026-08-28_at_4.03.19_PM.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916346/WhatsApp_Image_2026-08-28_at_4.03.19_PM.jpg',
    ],
    category: 'Kota Handloom',
    collections: ['kota-collection'],
    fabric: '—',
    weave: '—',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    isNew: true,
    description: 'With Blouse. Free Shipping.',
  },
  {
    slug: 'kota-handloom-saree-new-collection-03',
    name: 'Kota Handloom Saree — New Collection 03',
    price: 4700,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916345/WhatsApp_Image_2026-08-28_at_4.03.19_PM_1.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916345/WhatsApp_Image_2026-08-28_at_4.03.19_PM_1.jpg',
    ],
    category: 'Kota Handloom',
    collections: ['kota-collection'],
    fabric: '—',
    weave: '—',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    isNew: true,
    description: 'With Blouse. Free Shipping.',
  },
  {
    slug: 'kota-handloom-saree-new-collection-04',
    name: 'Kota Handloom Saree — New Collection 04',
    price: 4700,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916345/WhatsApp_Image_2026-08-28_at_4.03.19_PM_2.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916345/WhatsApp_Image_2026-08-28_at_4.03.19_PM_2.jpg',
    ],
    category: 'Kota Handloom',
    collections: ['kota-collection'],
    fabric: '—',
    weave: '—',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    isNew: true,
    description: 'With Blouse. Free Shipping.',
  },
  {
    slug: 'kota-handloom-saree-new-collection-05',
    name: 'Kota Handloom Saree — New Collection 05',
    price: 4700,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916344/WhatsApp_Image_2026-08-28_at_4.03.18_PM.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916344/WhatsApp_Image_2026-08-28_at_4.03.18_PM.jpg',
    ],
    category: 'Kota Handloom',
    collections: ['kota-collection'],
    fabric: '—',
    weave: '—',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    isNew: true,
    description: 'With Blouse. Free Shipping.',
  },
  {
    slug: 'kota-handloom-saree-new-collection-06',
    name: 'Kota Handloom Saree — New Collection 06',
    price: 4700,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916344/WhatsApp_Image_2026-08-28_at_4.03.18_PM_1.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916344/WhatsApp_Image_2026-08-28_at_4.03.18_PM_1.jpg',
    ],
    category: 'Kota Handloom',
    collections: ['kota-collection'],
    fabric: '—',
    weave: '—',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    isNew: true,
    description: 'With Blouse. Free Shipping.',
  },
  {
    slug: 'digital-print-saree-01',
    name: 'Green Floral Soft Silk Digital Print Saree',
    price: 1,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916480/WhatsApp_Image_2026-08-28_at_4.02.45_PM.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916480/WhatsApp_Image_2026-08-28_at_4.02.45_PM.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-02',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916480/WhatsApp_Image_2026-08-28_at_4.02.44_PM.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916480/WhatsApp_Image_2026-08-28_at_4.02.44_PM.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-03',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916479/WhatsApp_Image_2026-08-28_at_4.02.44_PM_2.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916479/WhatsApp_Image_2026-08-28_at_4.02.44_PM_2.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-04',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916478/WhatsApp_Image_2026-08-28_at_4.02.44_PM_1.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916478/WhatsApp_Image_2026-08-28_at_4.02.44_PM_1.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-05',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916477/WhatsApp_Image_2026-08-28_at_4.02.43_PM.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916477/WhatsApp_Image_2026-08-28_at_4.02.43_PM.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-06',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916476/WhatsApp_Image_2026-08-28_at_4.02.43_PM_2.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916476/WhatsApp_Image_2026-08-28_at_4.02.43_PM_2.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-07',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916475/WhatsApp_Image_2026-08-28_at_4.02.43_PM_1.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916475/WhatsApp_Image_2026-08-28_at_4.02.43_PM_1.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-08',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916474/WhatsApp_Image_2026-08-28_at_4.02.42_PM.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916474/WhatsApp_Image_2026-08-28_at_4.02.42_PM.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-09',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916473/WhatsApp_Image_2026-08-28_at_4.02.42_PM_2.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916473/WhatsApp_Image_2026-08-28_at_4.02.42_PM_2.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-10',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916472/WhatsApp_Image_2026-08-28_at_4.02.42_PM_1.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916472/WhatsApp_Image_2026-08-28_at_4.02.42_PM_1.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-11',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916471/WhatsApp_Image_2026-08-28_at_4.02.41_PM.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916471/WhatsApp_Image_2026-08-28_at_4.02.41_PM.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-12',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916471/WhatsApp_Image_2026-08-28_at_4.02.41_PM_1.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916471/WhatsApp_Image_2026-08-28_at_4.02.41_PM_1.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-13',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916470/WhatsApp_Image_2026-08-28_at_4.02.40_PM.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916470/WhatsApp_Image_2026-08-28_at_4.02.40_PM.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-14',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916469/WhatsApp_Image_2026-08-28_at_4.02.40_PM_3.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916469/WhatsApp_Image_2026-08-28_at_4.02.40_PM_3.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-15',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916468/WhatsApp_Image_2026-08-28_at_4.02.40_PM_2.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916468/WhatsApp_Image_2026-08-28_at_4.02.40_PM_2.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-16',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916467/WhatsApp_Image_2026-08-28_at_4.02.40_PM_1.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916467/WhatsApp_Image_2026-08-28_at_4.02.40_PM_1.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-17',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916466/WhatsApp_Image_2026-08-28_at_4.02.39_PM.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916466/WhatsApp_Image_2026-08-28_at_4.02.39_PM.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-18',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916465/WhatsApp_Image_2026-08-28_at_4.02.39_PM_2.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916465/WhatsApp_Image_2026-08-28_at_4.02.39_PM_2.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-19',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916464/WhatsApp_Image_2026-08-28_at_4.02.39_PM_1.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916464/WhatsApp_Image_2026-08-28_at_4.02.39_PM_1.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-20',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916463/WhatsApp_Image_2026-08-28_at_4.02.38_PM.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916463/WhatsApp_Image_2026-08-28_at_4.02.38_PM.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-21',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916462/WhatsApp_Image_2026-08-28_at_4.02.38_PM_2.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916462/WhatsApp_Image_2026-08-28_at_4.02.38_PM_2.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-22',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916462/WhatsApp_Image_2026-08-28_at_4.02.38_PM_1.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916462/WhatsApp_Image_2026-08-28_at_4.02.38_PM_1.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-23',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916461/WhatsApp_Image_2026-08-28_at_4.02.37_PM.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916461/WhatsApp_Image_2026-08-28_at_4.02.37_PM.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-24',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916460/WhatsApp_Image_2026-08-28_at_4.02.37_PM_2.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916460/WhatsApp_Image_2026-08-28_at_4.02.37_PM_2.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-25',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916459/WhatsApp_Image_2026-08-28_at_4.02.37_PM_1.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916459/WhatsApp_Image_2026-08-28_at_4.02.37_PM_1.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-26',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916458/WhatsApp_Image_2026-08-28_at_4.02.36_PM.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916458/WhatsApp_Image_2026-08-28_at_4.02.36_PM.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-27',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916457/WhatsApp_Image_2026-08-28_at_4.02.36_PM_2.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916457/WhatsApp_Image_2026-08-28_at_4.02.36_PM_2.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-28',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916456/WhatsApp_Image_2026-08-28_at_4.02.36_PM_1.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916456/WhatsApp_Image_2026-08-28_at_4.02.36_PM_1.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-29',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916455/WhatsApp_Image_2026-08-28_at_4.02.35_PM.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916455/WhatsApp_Image_2026-08-28_at_4.02.35_PM.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-30',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916454/WhatsApp_Image_2026-08-28_at_4.02.35_PM_2.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916454/WhatsApp_Image_2026-08-28_at_4.02.35_PM_2.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-31',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916453/WhatsApp_Image_2026-08-28_at_4.02.35_PM_1.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916453/WhatsApp_Image_2026-08-28_at_4.02.35_PM_1.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-32',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916452/WhatsApp_Image_2026-08-28_at_4.02.34_PM.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916452/WhatsApp_Image_2026-08-28_at_4.02.34_PM.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-33',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916451/WhatsApp_Image_2026-08-28_at_4.02.34_PM_2.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916451/WhatsApp_Image_2026-08-28_at_4.02.34_PM_2.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-34',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916450/WhatsApp_Image_2026-08-28_at_4.02.34_PM_1.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916450/WhatsApp_Image_2026-08-28_at_4.02.34_PM_1.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-35',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916450/WhatsApp_Image_2026-08-28_at_4.02.33_PM.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916450/WhatsApp_Image_2026-08-28_at_4.02.33_PM.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-36',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916449/WhatsApp_Image_2026-08-28_at_4.02.33_PM_2.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916449/WhatsApp_Image_2026-08-28_at_4.02.33_PM_2.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-37',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916448/WhatsApp_Image_2026-08-28_at_4.02.33_PM_1.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916448/WhatsApp_Image_2026-08-28_at_4.02.33_PM_1.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-38',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916447/WhatsApp_Image_2026-08-28_at_4.02.32_PM.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916447/WhatsApp_Image_2026-08-28_at_4.02.32_PM.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-39',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916446/WhatsApp_Image_2026-08-28_at_4.02.32_PM_2.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916446/WhatsApp_Image_2026-08-28_at_4.02.32_PM_2.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-40',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916445/WhatsApp_Image_2026-08-28_at_4.02.32_PM_1.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916445/WhatsApp_Image_2026-08-28_at_4.02.32_PM_1.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-41',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916444/WhatsApp_Image_2026-08-28_at_4.02.31_PM.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916444/WhatsApp_Image_2026-08-28_at_4.02.31_PM.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-42',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916443/WhatsApp_Image_2026-08-28_at_4.02.31_PM_2.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916443/WhatsApp_Image_2026-08-28_at_4.02.31_PM_2.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-43',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916442/WhatsApp_Image_2026-08-28_at_4.02.31_PM_1.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916442/WhatsApp_Image_2026-08-28_at_4.02.31_PM_1.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-44',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916441/WhatsApp_Image_2026-08-28_at_4.02.30_PM.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916441/WhatsApp_Image_2026-08-28_at_4.02.30_PM.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-45',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916440/WhatsApp_Image_2026-08-28_at_4.02.30_PM_2.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916440/WhatsApp_Image_2026-08-28_at_4.02.30_PM_2.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-46',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916439/WhatsApp_Image_2026-08-28_at_4.02.30_PM_1.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916439/WhatsApp_Image_2026-08-28_at_4.02.30_PM_1.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-47',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916438/WhatsApp_Image_2026-08-28_at_4.02.29_PM.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916438/WhatsApp_Image_2026-08-28_at_4.02.29_PM.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-48',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916437/WhatsApp_Image_2026-08-28_at_4.02.29_PM_2.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916437/WhatsApp_Image_2026-08-28_at_4.02.29_PM_2.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-49',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916436/WhatsApp_Image_2026-08-28_at_4.02.29_PM_1.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916436/WhatsApp_Image_2026-08-28_at_4.02.29_PM_1.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-50',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916435/WhatsApp_Image_2026-08-28_at_4.02.28_PM.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916435/WhatsApp_Image_2026-08-28_at_4.02.28_PM.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-51',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916434/WhatsApp_Image_2026-08-28_at_4.02.28_PM_2.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916434/WhatsApp_Image_2026-08-28_at_4.02.28_PM_2.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-52',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916433/WhatsApp_Image_2026-08-28_at_4.02.28_PM_1.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916433/WhatsApp_Image_2026-08-28_at_4.02.28_PM_1.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-53',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916432/WhatsApp_Image_2026-08-28_at_4.02.27_PM.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916432/WhatsApp_Image_2026-08-28_at_4.02.27_PM.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-54',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916431/WhatsApp_Image_2026-08-28_at_4.02.27_PM_2.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916431/WhatsApp_Image_2026-08-28_at_4.02.27_PM_2.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-55',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916430/WhatsApp_Image_2026-08-28_at_4.02.27_PM_1.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916430/WhatsApp_Image_2026-08-28_at_4.02.27_PM_1.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-56',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916429/WhatsApp_Image_2026-08-28_at_4.02.26_PM.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916429/WhatsApp_Image_2026-08-28_at_4.02.26_PM.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-57',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916428/WhatsApp_Image_2026-08-28_at_4.02.26_PM_2.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916428/WhatsApp_Image_2026-08-28_at_4.02.26_PM_2.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-58',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916427/WhatsApp_Image_2026-08-28_at_4.02.26_PM_1.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916427/WhatsApp_Image_2026-08-28_at_4.02.26_PM_1.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-59',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916426/WhatsApp_Image_2026-08-28_at_4.02.25_PM.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916426/WhatsApp_Image_2026-08-28_at_4.02.25_PM.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-60',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916425/WhatsApp_Image_2026-08-28_at_4.02.25_PM_2.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916425/WhatsApp_Image_2026-08-28_at_4.02.25_PM_2.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-61',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916424/WhatsApp_Image_2026-08-28_at_4.02.25_PM_1.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916424/WhatsApp_Image_2026-08-28_at_4.02.25_PM_1.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-62',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916424/WhatsApp_Image_2026-08-28_at_4.02.24_PM.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916424/WhatsApp_Image_2026-08-28_at_4.02.24_PM.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-63',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916423/WhatsApp_Image_2026-08-28_at_4.02.24_PM_2.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916423/WhatsApp_Image_2026-08-28_at_4.02.24_PM_2.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-64',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916422/WhatsApp_Image_2026-08-28_at_4.02.24_PM_1.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916422/WhatsApp_Image_2026-08-28_at_4.02.24_PM_1.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-65',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916421/WhatsApp_Image_2026-08-28_at_4.02.23_PM.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916421/WhatsApp_Image_2026-08-28_at_4.02.23_PM.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-66',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916420/WhatsApp_Image_2026-08-28_at_4.02.23_PM_2.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916420/WhatsApp_Image_2026-08-28_at_4.02.23_PM_2.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-67',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916419/WhatsApp_Image_2026-08-28_at_4.02.23_PM_1.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916419/WhatsApp_Image_2026-08-28_at_4.02.23_PM_1.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-68',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916418/WhatsApp_Image_2026-08-28_at_4.02.22_PM.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916418/WhatsApp_Image_2026-08-28_at_4.02.22_PM.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-69',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916417/WhatsApp_Image_2026-08-28_at_4.02.22_PM_2.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916417/WhatsApp_Image_2026-08-28_at_4.02.22_PM_2.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-70',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916416/WhatsApp_Image_2026-08-28_at_4.02.22_PM_1.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916416/WhatsApp_Image_2026-08-28_at_4.02.22_PM_1.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'digital-print-saree-71',
    name: 'Soft Silk Digital Print Saree',
    price: 2460,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916415/WhatsApp_Image_2026-08-28_at_4.02.21_PM.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1787916415/WhatsApp_Image_2026-08-28_at_4.02.21_PM.jpg',
    ],
    category: 'Digital Print',
    collections: [],
    fabric: 'Soft Silk',
    weave: 'Digital Print',
    length: '—',
    blouse: 'With Blouse',
    care: '—',
    availability: 'In Stock',
    description: 'Soft silk digital print saree with digital print work, paired with a blouse. Free shipping.',
  },
  {
    slug: 'chhabili-lehenga-set',
    name: 'CHHABILI',
    price: 3999,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789022729/WhatsApp_Image_2026-09-10_at_11.16.51_AM.jpg',
    // Catalog #1 (white/blue): keep all existing; append video last.
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789022729/WhatsApp_Image_2026-09-10_at_11.16.51_AM.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789022728/WhatsApp_Image_2026-09-10_at_11.16.49_AM_1.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789022728/WhatsApp_Image_2026-09-10_at_11.16.47_AM_2.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789022729/WhatsApp_Image_2026-09-10_at_11.16.50_AM.jpg',
      'https://res.cloudinary.com/tcjtyr02/video/upload/v1789109600/WhatsApp_Video_2026-09-10_at_11.25.27_AM.mp4',
    ],
    category: 'CHHABILI',
    collections: ['chhabili', 'navratri-collection'],
    fabric: 'Pure Cotton',
    weave: 'Lehenga Set · Kashida & Gamthi Work',
    length: '41" · 8 meter flair with canvas & inner',
    blouse: 'Top 38" (adj. 36"–40") · Top Length 25" · Waist up to 42"',
    care: 'Package: Lehenga, Top, Purse · Weight: 1.300 Kg',
    availability: 'In Stock',
    isNew: true,
    description:
      'Designed for Pure Cotton, this graceful lehenga features intricate Kashida and gamthi Work on the top, paired with a charming matching Purse for a complete festive look.\n\nPerfect for Navratri, Garba nights, festive gatherings & special celebrations.\n\nSpecifications:\n✦ Designed with 8 meter flair and stitching with canvas & inner\n✧ Length: 41"\n◇ Waist: Fits Up To 42"\n❖ Top: 38" standard sizing\n✦ Top adjustable margin: 36"–40"\n◇ Top Length: 25"\n\nPackage Contains:\n✦ Lehenga\n✧ Top\n◇ Purse\n\nWeight:\n◇ 1.300 Kg',
  },
  {
    slug: 'chhabili-lehenga-set-03',
    name: 'CHHABILI',
    price: 3999,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789022729/WhatsApp_Image_2026-09-10_at_11.16.50_AM_2.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789022729/WhatsApp_Image_2026-09-10_at_11.16.50_AM_2.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789022728/WhatsApp_Image_2026-09-10_at_11.16.49_AM.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789022728/WhatsApp_Image_2026-09-10_at_11.16.47_AM_2.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789022728/WhatsApp_Image_2026-09-10_at_11.16.49_AM_2.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789022728/WhatsApp_Image_2026-09-10_at_11.16.48_AM.jpg',
      'https://res.cloudinary.com/tcjtyr02/video/upload/v1789109601/WhatsApp_Video_2026-09-10_at_11.25.35_AM.mp4',
    ],
    category: 'CHHABILI',
    collections: ['chhabili', 'navratri-collection'],
    fabric: 'Pure Cotton',
    weave: 'Lehenga Set · Kashida & Gamthi Work',
    length: '41" · 8 meter flair with canvas & inner',
    blouse: 'Top 38" (adj. 36"–40") · Top Length 25" · Waist up to 42"',
    care: 'Package: Lehenga, Top, Purse · Weight: 1.300 Kg',
    availability: 'In Stock',
    isNew: true,
    description:
      'Designed for Pure Cotton, this graceful lehenga features intricate Kashida and gamthi Work on the top, paired with a charming matching Purse for a complete festive look.\n\nPerfect for Navratri, Garba nights, festive gatherings & special celebrations.\n\nSpecifications:\n✦ Designed with 8 meter flair and stitching with canvas & inner\n✧ Length: 41"\n◇ Waist fits up to 42"\n❖ Top 38" standard sizing\n✦ Top adjustable margin 36"–40"\n◇ Top Length 25"\n\nPackage Contains:\n✦ Lehenga\n✦ Top\n✦ Purse\n\nWeight:\n◇ 1.300 Kg',
  },
  {
    slug: 'chhabili-lehenga-set-04',
    name: 'CHHABILI',
    price: 3999,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789022727/WhatsApp_Image_2026-09-10_at_11.16.46_AM_2.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789022727/WhatsApp_Image_2026-09-10_at_11.16.46_AM_2.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789022728/WhatsApp_Image_2026-09-10_at_11.16.50_AM_1.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789022728/WhatsApp_Image_2026-09-10_at_11.16.47_AM.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789022727/WhatsApp_Image_2026-09-10_at_11.16.47_AM_1.jpg',
      'https://res.cloudinary.com/tcjtyr02/video/upload/v1789109611/WhatsApp_Video_2026-09-10_at_11.25.26_AM_1.mp4',
      'https://res.cloudinary.com/tcjtyr02/video/upload/v1789109601/WhatsApp_Video_2026-09-10_at_11.25.26_AM.mp4',
    ],
    category: 'CHHABILI',
    collections: ['chhabili', 'navratri-collection'],
    fabric: 'Pure Cotton',
    weave: 'Lehenga Set · Kashida & Gamthi Work',
    length: '41" · 8 meter flair with canvas & inner',
    blouse: 'Top 38" (adj. 36"–40") · Top Length 25" · Waist up to 42"',
    care: 'Package: Lehenga, Top, Purse · Weight: 1.300 Kg',
    availability: 'In Stock',
    isNew: true,
    description:
      'Designed for Pure Cotton, this graceful lehenga features intricate Kashida and gamthi Work on the top, paired with a charming matching Purse for a complete festive look.\n\nPerfect for Navratri, Garba nights, festive gatherings & special celebrations.\n\nSpecifications:\n✦ Designed with 8 meter flair and stitching with canvas & inner\n✧ Length: 41"\n◇ Waist fits up to 42"\n❖ Top 38" standard sizing\n✦ Top adjustable margin 36"–40"\n◇ Top Length 25"\n\nPackage Contains:\n✦ Lehenga\n✦ Top\n✦ Purse\n\nWeight:\n◇ 1.300 Kg',
  },
  {
    slug: 'chhabili-lehenga-set-05',
    name: 'CHHABILI',
    price: 3999,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789022727/WhatsApp_Image_2026-09-10_at_11.16.46_AM_1.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789022727/WhatsApp_Image_2026-09-10_at_11.16.46_AM_1.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789022727/WhatsApp_Image_2026-09-10_at_11.16.45_AM.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789022727/WhatsApp_Image_2026-09-10_at_11.16.45_AM_1.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789022727/WhatsApp_Image_2026-09-10_at_11.16.46_AM.jpg',
      'https://res.cloudinary.com/tcjtyr02/video/upload/v1789109603/WhatsApp_Video_2026-09-10_at_11.25.36_AM.mp4',
    ],
    category: 'CHHABILI',
    collections: ['chhabili', 'navratri-collection'],
    fabric: 'Pure Cotton',
    weave: 'Lehenga Set · Kashida & Gamthi Work',
    length: '41" · 8 meter flair with canvas & inner',
    blouse: 'Top 38" (adj. 36"–40") · Top Length 25" · Waist up to 42"',
    care: 'Package: Lehenga, Top, Purse · Weight: 1.300 Kg',
    availability: 'In Stock',
    isNew: true,
    description:
      'Designed for Pure Cotton, this graceful lehenga features intricate Kashida and gamthi Work on the top, paired with a charming matching Purse for a complete festive look.\n\nPerfect for Navratri, Garba nights, festive gatherings & special celebrations.\n\nSpecifications:\n✦ Designed with 8 meter flair and stitching with canvas & inner\n✧ Length: 41"\n◇ Waist fits up to 42"\n❖ Top 38" standard sizing\n✦ Top adjustable margin 36"–40"\n◇ Top Length 25"\n\nPackage Contains:\n✦ Lehenga\n✦ Top\n✦ Purse\n\nWeight:\n◇ 1.300 Kg',
  },
  {
    slug: 'lehanga-kanjiveram-silk',
    name: 'LEHANGA',
    price: 2690,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789041228/WhatsApp_Image_2026-09-10_at_11.18.13_AM_1.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789041228/WhatsApp_Image_2026-09-10_at_11.18.13_AM_1.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789041229/WhatsApp_Image_2026-09-10_at_11.18.13_AM.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789041224/WhatsApp_Image_2026-09-10_at_11.18.10_AM.jpg',
      'https://res.cloudinary.com/tcjtyr02/video/upload/v1789041231/WhatsApp_Video_2026-09-10_at_11.18.06_AM.mp4',
    ],
    category: 'Lehenga Collection',
    collections: ['lehanga', 'navratri-collection'],
    fabric: 'Pure Kanjiveram Silk',
    weave: 'Lehenga Set · Jacquard Border · Maggam Work Blouse',
    length: '42" · 4 mtr flair with canvas patta',
    blouse: 'Full stitched Rangoli · Free size · Designer work sleeves',
    care: 'Package: Lehenga, Blouse, Dupatta',
    availability: 'In Stock',
    isNew: true,
    description:
      'Launch New Exclusive Designer premium Quality pure Kanjiveram silk full stitched Lehenga with Full stitched Designer maggam work blouse with embroidered work Dupatta.\n\nProduct Details:\n✦ Lehenga: Full stitched Kanjiveram silk with big Jacquard Border attached with canvas patta\n✦ Length: 42"\n✦ Flair: 4 mtr\n\n✦ Blouse: Full stitched Rangoli with heavy designer work on back and front with designer work sleeve\n✦ Size: Free size\n\n✦ Dupatta: Premium Quality Rangoli silk with beautiful embroidery cutwork border',
  },
  {
    slug: 'lehanga-02',
    name: 'LEHANGA',
    price: 2690,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789041229/WhatsApp_Image_2026-09-10_at_11.18.13_AM_2.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789041229/WhatsApp_Image_2026-09-10_at_11.18.13_AM_2.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789041224/WhatsApp_Image_2026-09-10_at_11.18.11_AM_1.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789041222/WhatsApp_Image_2026-09-10_at_11.18.10_AM_1.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789041218/WhatsApp_Image_2026-09-10_at_11.18.07_AM_2.jpg',
    ],
    category: 'Lehenga Collection',
    collections: ['lehanga', 'navratri-collection'],
    fabric: 'Pure Kanjiveram Silk',
    weave: 'Lehenga Set · Jacquard Border · Maggam Work Blouse',
    length: '42" · 4 mtr flair with canvas patta',
    blouse: 'Full stitched Rangoli · Free size · Designer work sleeves',
    care: 'Package: Lehenga, Blouse, Dupatta',
    availability: 'In Stock',
    isNew: true,
    description:
      'Launch New Exclusive Designer premium Quality pure Kanjiveram silk full stitched Lehenga with Full stitched Designer maggam work blouse with embroidered work Dupatta.\n\nProduct Details:\n✦ Lehenga: Full stitched Kanjiveram silk with big Jacquard Border attached with canvas patta\n✦ Length: 42"\n✦ Flair: 4 mtr\n\n✦ Blouse: Full stitched Rangoli with heavy designer work on back and front with designer work sleeve\n✦ Size: Free size\n\n✦ Dupatta: Premium Quality Rangoli silk with beautiful embroidery cutwork border',
  },
  {
    slug: 'kanchipuram-silk-lehenga',
    name: 'KANCHIPURAM SILK LEHENGA',
    price: 1950,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789113689/WhatsApp_Image_2026-09-10_at_11.26.34_AM.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789113689/WhatsApp_Image_2026-09-10_at_11.26.34_AM.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789113677/WhatsApp_Image_2026-09-10_at_11.26.30_AM_2.jpg',
    ],
    category: 'Lehenga Collection',
    collections: ['lehanga', 'navratri-collection'],
    fabric: 'Kanchipuram',
    weave: 'Zari Weaving Work',
    length: '41" · 3.70 meter flair · stitch with canvas',
    blouse: 'Unstitched · 0.80 Meter · Zari Weaving Work',
    care: 'Package: Lehenga, Blouse, Dupatta, Drawstring · Weight: 1 kg',
    availability: 'In Stock',
    isNew: true,
    description:
      'Crafted with love, adorned with heritage : The South-style Kanchipuram silk lehenga is more than just attire; it\'s a piece of art that encapsulates the essence of South Indian culture 🪸\n\nLehenga (Stitched)\n✦ Lehenga Fabric: Kanchipuram\n✦ Lehenga Work: Zari Weaving Work\n✦ Lehenga Waist: SUPPORTED UP TO 42\n✦ Lehenga Closer: Drawstring With Zip\n✦ Stitching: Stitch With Canvas\n✦ Length: 41\n✦ Flair: 3.70 Meter\n✦ Inner: Micro Cotton\n\nBlouse (Unstitched)\n✦ Blouse Fabric: Kanchipuram\n✦ Blouse Work: Zari Weaving Work\n✦ Blouse Length: 0.80 Meter\n\nDupatta\n✦ Dupatta Fabric: Georgette\n✦ Dupatta Work: Plain With Lase Border\n✦ Dupatta Length: 2.5 Meter\n\nPackage Contains:\n✧ Lehenga\n✧ Blouse\n✧ Dupatta\n✧ Drawstring\n\nWeight:\n◇ 1 kg\n\nRate:\n❖ ₹1,950',
  },
  {
    slug: 'kanchipuram-silk-lehenga-02',
    name: 'KANCHIPURAM SILK LEHENGA',
    price: 1950,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789113686/WhatsApp_Image_2026-09-10_at_11.26.33_AM.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789113686/WhatsApp_Image_2026-09-10_at_11.26.33_AM.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789113679/WhatsApp_Image_2026-09-10_at_11.26.31_AM_1.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789113275/WhatsApp_Image_2026-09-10_at_11.26.25_AM.jpg',
    ],
    category: 'Lehenga Collection',
    collections: ['lehanga', 'navratri-collection'],
    fabric: 'Kanchipuram',
    weave: 'Zari Weaving Work',
    length: '41" · 3.70 meter flair · stitch with canvas',
    blouse: 'Unstitched · 0.80 Meter · Zari Weaving Work',
    care: 'Package: Lehenga, Blouse, Dupatta, Drawstring · Weight: 1 kg',
    availability: 'In Stock',
    isNew: true,
    description:
      'Crafted with love, adorned with heritage : The South-style Kanchipuram silk lehenga is more than just attire; it\'s a piece of art that encapsulates the essence of South Indian culture 🪸\n\nLehenga (Stitched)\n✦ Lehenga Fabric: Kanchipuram\n✦ Lehenga Work: Zari Weaving Work\n✦ Lehenga Waist: SUPPORTED UP TO 42\n✦ Lehenga Closer: Drawstring With Zip\n✦ Stitching: Stitch With Canvas\n✦ Length: 41\n✦ Flair: 3.70 Meter\n✦ Inner: Micro Cotton\n\nBlouse (Unstitched)\n✦ Blouse Fabric: Kanchipuram\n✦ Blouse Work: Zari Weaving Work\n✦ Blouse Length: 0.80 Meter\n\nDupatta\n✦ Dupatta Fabric: Georgette\n✦ Dupatta Work: Plain With Lase Border\n✦ Dupatta Length: 2.5 Meter\n\nPackage Contains:\n✧ Lehenga\n✧ Blouse\n✧ Dupatta\n✧ Drawstring\n\nWeight:\n◇ 1 kg\n\nRate:\n❖ ₹1,950',
  },
  {
    slug: 'kanchipuram-silk-lehenga-03',
    name: 'KANCHIPURAM SILK LEHENGA',
    price: 1950,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789113684/WhatsApp_Image_2026-09-10_at_11.26.32_AM.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789113684/WhatsApp_Image_2026-09-10_at_11.26.32_AM.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789113670/WhatsApp_Image_2026-09-10_at_11.26.26_AM.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789113671/WhatsApp_Image_2026-09-10_at_11.26.27_AM.jpg',
    ],
    category: 'Lehenga Collection',
    collections: ['lehanga', 'navratri-collection'],
    fabric: 'Kanchipuram',
    weave: 'Zari Weaving Work',
    length: '41" · 3.70 meter flair · stitch with canvas',
    blouse: 'Unstitched · 0.80 Meter · Zari Weaving Work',
    care: 'Package: Lehenga, Blouse, Dupatta, Drawstring · Weight: 1 kg',
    availability: 'In Stock',
    isNew: true,
    description:
      'Crafted with love, adorned with heritage : The South-style Kanchipuram silk lehenga is more than just attire; it\'s a piece of art that encapsulates the essence of South Indian culture 🪸\n\nLehenga (Stitched)\n✦ Lehenga Fabric: Kanchipuram\n✦ Lehenga Work: Zari Weaving Work\n✦ Lehenga Waist: SUPPORTED UP TO 42\n✦ Lehenga Closer: Drawstring With Zip\n✦ Stitching: Stitch With Canvas\n✦ Length: 41\n✦ Flair: 3.70 Meter\n✦ Inner: Micro Cotton\n\nBlouse (Unstitched)\n✦ Blouse Fabric: Kanchipuram\n✦ Blouse Work: Zari Weaving Work\n✦ Blouse Length: 0.80 Meter\n\nDupatta\n✦ Dupatta Fabric: Georgette\n✦ Dupatta Work: Plain With Lase Border\n✦ Dupatta Length: 2.5 Meter\n\nPackage Contains:\n✧ Lehenga\n✧ Blouse\n✧ Dupatta\n✧ Drawstring\n\nWeight:\n◇ 1 kg\n\nRate:\n❖ ₹1,950',
  },
  {
    slug: 'kanchipuram-silk-lehenga-04',
    name: 'KANCHIPURAM SILK LEHENGA',
    price: 1950,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789113676/WhatsApp_Image_2026-09-10_at_11.26.30_AM_1.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789113676/WhatsApp_Image_2026-09-10_at_11.26.30_AM_1.jpg',
    ],
    category: 'Lehenga Collection',
    collections: ['lehanga', 'navratri-collection'],
    fabric: 'Kanchipuram',
    weave: 'Zari Weaving Work',
    length: '41" · 3.70 meter flair · stitch with canvas',
    blouse: 'Unstitched · 0.80 Meter · Zari Weaving Work',
    care: 'Package: Lehenga, Blouse, Dupatta, Drawstring · Weight: 1 kg',
    availability: 'In Stock',
    isNew: true,
    description:
      'Crafted with love, adorned with heritage : The South-style Kanchipuram silk lehenga is more than just attire; it\'s a piece of art that encapsulates the essence of South Indian culture 🪸\n\nLehenga (Stitched)\n✦ Lehenga Fabric: Kanchipuram\n✦ Lehenga Work: Zari Weaving Work\n✦ Lehenga Waist: SUPPORTED UP TO 42\n✦ Lehenga Closer: Drawstring With Zip\n✦ Stitching: Stitch With Canvas\n✦ Length: 41\n✦ Flair: 3.70 Meter\n✦ Inner: Micro Cotton\n\nBlouse (Unstitched)\n✦ Blouse Fabric: Kanchipuram\n✦ Blouse Work: Zari Weaving Work\n✦ Blouse Length: 0.80 Meter\n\nDupatta\n✦ Dupatta Fabric: Georgette\n✦ Dupatta Work: Plain With Lase Border\n✦ Dupatta Length: 2.5 Meter\n\nPackage Contains:\n✧ Lehenga\n✧ Blouse\n✧ Dupatta\n✧ Drawstring\n\nWeight:\n◇ 1 kg\n\nRate:\n❖ ₹1,950',
  },
  {
    slug: 'kanchipuram-silk-lehenga-05',
    name: 'KANCHIPURAM SILK LEHENGA',
    price: 1950,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789113674/WhatsApp_Image_2026-09-10_at_11.26.29_AM.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789113674/WhatsApp_Image_2026-09-10_at_11.26.29_AM.jpg',
    ],
    category: 'Lehenga Collection',
    collections: ['lehanga', 'navratri-collection'],
    fabric: 'Kanchipuram',
    weave: 'Zari Weaving Work',
    length: '41" · 3.70 meter flair · stitch with canvas',
    blouse: 'Unstitched · 0.80 Meter · Zari Weaving Work',
    care: 'Package: Lehenga, Blouse, Dupatta, Drawstring · Weight: 1 kg',
    availability: 'In Stock',
    isNew: true,
    description:
      'Crafted with love, adorned with heritage : The South-style Kanchipuram silk lehenga is more than just attire; it\'s a piece of art that encapsulates the essence of South Indian culture 🪸\n\nLehenga (Stitched)\n✦ Lehenga Fabric: Kanchipuram\n✦ Lehenga Work: Zari Weaving Work\n✦ Lehenga Waist: SUPPORTED UP TO 42\n✦ Lehenga Closer: Drawstring With Zip\n✦ Stitching: Stitch With Canvas\n✦ Length: 41\n✦ Flair: 3.70 Meter\n✦ Inner: Micro Cotton\n\nBlouse (Unstitched)\n✦ Blouse Fabric: Kanchipuram\n✦ Blouse Work: Zari Weaving Work\n✦ Blouse Length: 0.80 Meter\n\nDupatta\n✦ Dupatta Fabric: Georgette\n✦ Dupatta Work: Plain With Lase Border\n✦ Dupatta Length: 2.5 Meter\n\nPackage Contains:\n✧ Lehenga\n✧ Blouse\n✧ Dupatta\n✧ Drawstring\n\nWeight:\n◇ 1 kg\n\nRate:\n❖ ₹1,950',
  },
  {
    slug: 'kanchipuram-silk-lehenga-06',
    name: 'KANCHIPURAM SILK LEHENGA',
    price: 1950,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789113274/WhatsApp_Image_2026-09-10_at_11.26.25_AM_1.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789113274/WhatsApp_Image_2026-09-10_at_11.26.25_AM_1.jpg',
    ],
    category: 'Lehenga Collection',
    collections: ['lehanga', 'navratri-collection'],
    fabric: 'Kanchipuram',
    weave: 'Zari Weaving Work',
    length: '41" · 3.70 meter flair · stitch with canvas',
    blouse: 'Unstitched · 0.80 Meter · Zari Weaving Work',
    care: 'Package: Lehenga, Blouse, Dupatta, Drawstring · Weight: 1 kg',
    availability: 'In Stock',
    isNew: true,
    description:
      'Crafted with love, adorned with heritage : The South-style Kanchipuram silk lehenga is more than just attire; it\'s a piece of art that encapsulates the essence of South Indian culture 🪸\n\nLehenga (Stitched)\n✦ Lehenga Fabric: Kanchipuram\n✦ Lehenga Work: Zari Weaving Work\n✦ Lehenga Waist: SUPPORTED UP TO 42\n✦ Lehenga Closer: Drawstring With Zip\n✦ Stitching: Stitch With Canvas\n✦ Length: 41\n✦ Flair: 3.70 Meter\n✦ Inner: Micro Cotton\n\nBlouse (Unstitched)\n✦ Blouse Fabric: Kanchipuram\n✦ Blouse Work: Zari Weaving Work\n✦ Blouse Length: 0.80 Meter\n\nDupatta\n✦ Dupatta Fabric: Georgette\n✦ Dupatta Work: Plain With Lase Border\n✦ Dupatta Length: 2.5 Meter\n\nPackage Contains:\n✧ Lehenga\n✧ Blouse\n✧ Dupatta\n✧ Drawstring\n\nWeight:\n◇ 1 kg\n\nRate:\n❖ ₹1,950',
  },
  {
    slug: 'jobaniyu',
    name: 'JOBANIYU (જોબનિયું)',
    price: 2599,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789109341/WhatsApp_Image_2026-09-10_at_11.19.26_AM_1.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789109341/WhatsApp_Image_2026-09-10_at_11.19.26_AM_1.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789109341/WhatsApp_Image_2026-09-10_at_11.19.26_AM.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789109341/WhatsApp_Image_2026-09-10_at_11.19.25_AM_1.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789109341/WhatsApp_Image_2026-09-10_at_11.19.25_AM.jpg',
      'https://res.cloudinary.com/tcjtyr02/video/upload/v1789109786/1.mp4',
    ],
    category: 'JOBANIYU',
    collections: ['jobaniyu', 'navratri-collection'],
    fabric: 'Tasar Silk',
    weave: 'Gamthi Print · Embossed Design · Gotta Patti Lace',
    length: '41" · 3.80 meter flair · stitched with canvas & full inner',
    blouse: '38" (adj. up to 42") · Length 15" · Sleeve Length 11"',
    care: 'Package: Lehenga, Blouse, Dupatta, Drawstring with Zip · Weight: 1.100 kg',
    availability: 'In Stock',
    isNew: true,
    description:
      'From the looms of tradition to the rhythm of Garba — this Tassar silk lehenga with Gamthi print brings your Navratri dream to life in every swirl 🧿\n\nLehenga (Stitched)\n✦ Lehenga Fabric: Tasar Silk\n✦ Lehenga Work: Gamthi Print With Embossed Design And Gotta Patti Lace Touch Up\n✦ Lehenga Waist: Support Up To 42\n✦ Lehenga Closer: Drawstring With Zip\n✦ Stitching: Stitched With Canvas And Full Inner\n✦ Length: 41\n✦ Flair: 3.80 Meter\n✦ Inner: Micro Crepe\n\nBlouse (Stitched)\n✦ Blouse Fabric: Tasar Silk\n✦ Blouse Work: Gamthi Print With Embossed Design And Gotta Patti Lace Touch Up\n✦ Blouse Size: 38” There is Extra Margin Customer Can Adjust up to 42\n✦ Blouse Length: 15\n✦ Sleeve Length: 11\n\nDupatta\n✦ Dupatta Fabric: Tasar Silk\n✦ Dupatta Work: Gamthi Print With Gotta Patti Lace Touch Up\n✦ Dupatta Length: 2.40 Meter\n\nPackage Contains:\n✧ Lehenga\n✧ Blouse\n✧ Dupatta\n✧ Drawstring with Zip\n\nWeight:\n◇ 1.100 kg',
  },
  {
    slug: 'lehenga-choli',
    name: 'Lehenga Choli🌷',
    price: 1999,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789125875/WhatsApp_Image_2026-09-10_at_11.28.00_AM_1.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789125875/WhatsApp_Image_2026-09-10_at_11.28.00_AM_1.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789125870/WhatsApp_Image_2026-09-10_at_11.27.59_AM_2.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789125865/WhatsApp_Image_2026-09-10_at_11.27.58_AM.jpg',
    ],
    category: 'LEHENGA CHOLI',
    collections: ['lehenga-choli'],
    fabric: 'Dola Silk',
    weave: 'Kalmkaei Print · Embroidery Thread Work',
    length: '41" · 3.5 meter flair · stitched with canvas',
    blouse: 'Unstitched · Vichitra Silk · Embroidery Thread Work',
    care: 'Package: Lehenga, Blouse, Dupatta, Drawstring With Zip · Weight: 1 Kg',
    availability: 'In Stock',
    isNew: true,
    description:
      'Printed perfection for every occasion 🖤\n\nLehenga (Stitched)\n✦ Lehenga Fabric: Dola Silk\n✦ Lehenga Work: Kalmkaei Print\n✦ Lehenga Waist: Supported Up To 42\n✦ Lehenga Closer: Drawstring With Zip\n✦ Stitching: Stitched With Canvas\n✦ Length: 41\n✦ Flair: 3.5 Meter\n✦ Inner: Micro Cotton\n\nBlouse (Unstitched)\n✧ Blouse Fabric: Vichitra Silk\n✧ Work: Embroidery Thread Work\n\nDupatta\n◇ Dupatta Fabric: Vichitra Silk\n◇ Dupatta Work: Embroidery Thread Work With 4 Sard Lace Work\n◇ Dupatta Length: 2.5 Meter\n\nPackage Contains:\n❖ Lehenga\n❖ Blouse\n❖ Dupatta\n❖ Drawstring With Zip\n\nWeight:\n❖ 1 Kg\n\nRATE:\n₹1,999',
  },
  {
    slug: 'lehenga-choli-02',
    name: 'Lehenga Choli🌷',
    price: 1999,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789125861/WhatsApp_Image_2026-09-10_at_11.27.57_AM.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789125861/WhatsApp_Image_2026-09-10_at_11.27.57_AM.jpg',
    ],
    category: 'LEHENGA CHOLI',
    collections: ['lehenga-choli'],
    fabric: 'Dola Silk',
    weave: 'Kalmkaei Print · Embroidery Thread Work',
    length: '41" · 3.5 meter flair · stitched with canvas',
    blouse: 'Unstitched · Vichitra Silk · Embroidery Thread Work',
    care: 'Package: Lehenga, Blouse, Dupatta, Drawstring With Zip · Weight: 1 Kg',
    availability: 'In Stock',
    isNew: true,
    description:
      'Printed perfection for every occasion 🖤\n\nLehenga (Stitched)\n✦ Lehenga Fabric: Dola Silk\n✦ Lehenga Work: Kalmkaei Print\n✦ Lehenga Waist: Supported Up To 42\n✦ Lehenga Closer: Drawstring With Zip\n✦ Stitching: Stitched With Canvas\n✦ Length: 41\n✦ Flair: 3.5 Meter\n✦ Inner: Micro Cotton\n\nBlouse (Unstitched)\n✧ Blouse Fabric: Vichitra Silk\n✧ Work: Embroidery Thread Work\n\nDupatta\n◇ Dupatta Fabric: Vichitra Silk\n◇ Dupatta Work: Embroidery Thread Work With 4 Sard Lace Work\n◇ Dupatta Length: 2.5 Meter\n\nPackage Contains:\n❖ Lehenga\n❖ Blouse\n❖ Dupatta\n❖ Drawstring With Zip\n\nWeight:\n❖ 1 Kg\n\nRATE:\n₹1,999',
  },
  {
    slug: 'lehenga-choli-03',
    name: 'Lehenga Choli🌷',
    price: 1999,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789125868/WhatsApp_Image_2026-09-10_at_11.27.59_AM_1.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789125868/WhatsApp_Image_2026-09-10_at_11.27.59_AM_1.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789125873/WhatsApp_Image_2026-09-10_at_11.27.59_AM.jpg',
    ],
    category: 'LEHENGA CHOLI',
    collections: ['lehenga-choli'],
    fabric: 'Dola Silk',
    weave: 'Kalmkaei Print · Embroidery Thread Work',
    length: '41" · 3.5 meter flair · stitched with canvas',
    blouse: 'Unstitched · Vichitra Silk · Embroidery Thread Work',
    care: 'Package: Lehenga, Blouse, Dupatta, Drawstring With Zip · Weight: 1 Kg',
    availability: 'In Stock',
    isNew: true,
    description:
      'Printed perfection for every occasion 🖤\n\nLehenga (Stitched)\n✦ Lehenga Fabric: Dola Silk\n✦ Lehenga Work: Kalmkaei Print\n✦ Lehenga Waist: Supported Up To 42\n✦ Lehenga Closer: Drawstring With Zip\n✦ Stitching: Stitched With Canvas\n✦ Length: 41\n✦ Flair: 3.5 Meter\n✦ Inner: Micro Cotton\n\nBlouse (Unstitched)\n✧ Blouse Fabric: Vichitra Silk\n✧ Work: Embroidery Thread Work\n\nDupatta\n◇ Dupatta Fabric: Vichitra Silk\n◇ Dupatta Work: Embroidery Thread Work With 4 Sard Lace Work\n◇ Dupatta Length: 2.5 Meter\n\nPackage Contains:\n❖ Lehenga\n❖ Blouse\n❖ Dupatta\n❖ Drawstring With Zip\n\nWeight:\n❖ 1 Kg\n\nRATE:\n₹1,999',
  },
  {
    slug: 'lehenga-choli-04',
    name: 'Lehenga Choli🌷',
    price: 1999,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789125863/WhatsApp_Image_2026-09-10_at_11.27.58_AM_1.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789125863/WhatsApp_Image_2026-09-10_at_11.27.58_AM_1.jpg',
    ],
    category: 'LEHENGA CHOLI',
    collections: ['lehenga-choli'],
    fabric: 'Dola Silk',
    weave: 'Kalmkaei Print · Embroidery Thread Work',
    length: '41" · 3.5 meter flair · stitched with canvas',
    blouse: 'Unstitched · Vichitra Silk · Embroidery Thread Work',
    care: 'Package: Lehenga, Blouse, Dupatta, Drawstring With Zip · Weight: 1 Kg',
    availability: 'In Stock',
    isNew: true,
    description:
      'Printed perfection for every occasion 🖤\n\nLehenga (Stitched)\n✦ Lehenga Fabric: Dola Silk\n✦ Lehenga Work: Kalmkaei Print\n✦ Lehenga Waist: Supported Up To 42\n✦ Lehenga Closer: Drawstring With Zip\n✦ Stitching: Stitched With Canvas\n✦ Length: 41\n✦ Flair: 3.5 Meter\n✦ Inner: Micro Cotton\n\nBlouse (Unstitched)\n✧ Blouse Fabric: Vichitra Silk\n✧ Work: Embroidery Thread Work\n\nDupatta\n◇ Dupatta Fabric: Vichitra Silk\n◇ Dupatta Work: Embroidery Thread Work With 4 Sard Lace Work\n◇ Dupatta Length: 2.5 Meter\n\nPackage Contains:\n❖ Lehenga\n❖ Blouse\n❖ Dupatta\n❖ Drawstring With Zip\n\nWeight:\n❖ 1 Kg\n\nRATE:\n₹1,999',
  },
  {
    slug: 'dharvi-durga-pooja-edition',
    name: 'DHARVI — DURGA POOJA EDITION',
    price: 1250,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789206290/WhatsApp_Image_2026-09-11_at_2.18.16_PM.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789206290/WhatsApp_Image_2026-09-11_at_2.18.16_PM.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789206289/WhatsApp_Image_2026-09-11_at_2.18.16_PM_1.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789206288/WhatsApp_Image_2026-09-11_at_2.18.15_PM.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789206288/WhatsApp_Image_2026-09-11_at_2.18.15_PM_1.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789206287/WhatsApp_Image_2026-09-11_at_2.18.14_PM.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789206286/WhatsApp_Image_2026-09-11_at_2.18.14_PM_2.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789206286/WhatsApp_Image_2026-09-11_at_2.18.14_PM_1.jpg',
    ],
    category: 'DHARVI — DURGA POOJA EDITION',
    collections: ['dharvi-durga-pooja-edition'],
    fabric: 'Heavy Blooming Mul Cotton',
    weave: 'Gold Pattu Border · Allover',
    length: 'Saree with matching pallu',
    blouse: 'Perfectly matched blouse piece included',
    care: 'Quality & Fashion · New catalog',
    availability: 'In Stock',
    isNew: true,
    description:
      'ENJOY YOUR FESTIVALS WITH THIS SAREE\n\n🥻 Saree Fabric: Heavy blooming mul cotton saree with gold pattu border on allover saree with PERFECTLY MATCHED blouse piece and pallu\n\n✏️ We believe in Quality & Fashion in new catalog',
  },
  {
    slug: 'dharvi-durga-puja-collection',
    name: 'Dharvi Durga Puja Collection🇮🇳💫',
    price: 999,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789206372/WhatsApp_Image_2026-09-11_at_2.21.56_PM.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789206372/WhatsApp_Image_2026-09-11_at_2.21.56_PM.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789206373/WhatsApp_Image_2026-09-11_at_2.21.57_PM.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789206371/WhatsApp_Image_2026-09-11_at_2.21.56_PM_2.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789206370/WhatsApp_Image_2026-09-11_at_2.21.56_PM_1.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789206368/WhatsApp_Image_2026-09-11_at_2.21.55_PM_3.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789206369/WhatsApp_Image_2026-09-11_at_2.21.55_PM.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789206367/WhatsApp_Image_2026-09-11_at_2.21.55_PM_2.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789206366/WhatsApp_Image_2026-09-11_at_2.21.55_PM_1.jpg',
    ],
    category: 'DHARVI — DURGA POOJA EDITION',
    collections: ['dharvi-durga-pooja-edition'],
    fabric: 'Soft Linen Print & Blouse',
    weave: 'Linen Print',
    length: 'Saree with blouse',
    blouse: 'Matching blouse',
    care: "Let's Talk About Fashion💃🏼",
    availability: 'In Stock',
    isNew: true,
    description:
      '🥳Being Traditional Is Being Classy.\n\n🥳 Fabric: Soft Linen Print & Blouse\n\nLet\'s Talk About Fashion💃🏼',
  },
  {
    slug: 'dharvi-puja-collection',
    name: 'Dharvi puja collection',
    price: 1499,
    image:
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789206426/WhatsApp_Image_2026-09-11_at_2.22.56_PM.jpg',
    images: [
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789206426/WhatsApp_Image_2026-09-11_at_2.22.56_PM.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789206425/WhatsApp_Image_2026-09-11_at_2.22.55_PM.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789206424/WhatsApp_Image_2026-09-11_at_2.22.55_PM_3.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789206423/WhatsApp_Image_2026-09-11_at_2.22.55_PM_2.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789206422/WhatsApp_Image_2026-09-11_at_2.22.55_PM_1.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789206421/WhatsApp_Image_2026-09-11_at_2.22.54_PM.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789206420/WhatsApp_Image_2026-09-11_at_2.22.54_PM_2.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789206419/WhatsApp_Image_2026-09-11_at_2.22.54_PM_1.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789206418/WhatsApp_Image_2026-09-11_at_2.22.53_PM.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789206417/WhatsApp_Image_2026-09-11_at_2.22.53_PM_1.jpg',
      'https://res.cloudinary.com/tcjtyr02/image/upload/v1789206416/WhatsApp_Image_2026-09-11_at_2.22.51_PM.jpg',
    ],
    category: 'DHARVI — DURGA POOJA EDITION',
    collections: ['dharvi-durga-pooja-edition'],
    fabric: 'Soft Linen Gold Zari Border',
    weave: 'Digital Print',
    length: '6.30 Meter (With Digital Matching Blouse)',
    blouse: 'Soft Linen with Digital Print Matching Blouse',
    care: 'Digital Print · Soft Linen',
    availability: 'In Stock',
    isNew: true,
    description:
      '🍁 Dharvi puja collection\n\nFabric: Soft Linen Gold Zari Border\n\nWork: Digital Print\n\nSaree Length: 6.30 Meter\n(With Digital Matching Blouse)\n\nBlouse Fabric: Soft Linen with Digital Print Matching Blouse\n\n🍁🍁🍁🍁🍁🍁',
  },
]

export function getProduct(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug)
}

/**
 * Fallback createdAt for static catalog rows when DB timestamps are unavailable.
 * Later entries in `products` are treated as more recently added.
 */
const CATALOG_FALLBACK_EPOCH_MS = Date.UTC(2024, 0, 1)

export function withCatalogCreatedAt(list: Product[]): Product[] {
  return list.map((product, index) => {
    if (product.createdAt) return product
    return {
      ...product,
      createdAt: new Date(CATALOG_FALLBACK_EPOCH_MS + index * 60_000).toISOString(),
    }
  })
}

/** Catalog products visible on the storefront (respects temporary payment test mode). */
export function getStorefrontProducts(): Product[] {
  return withCatalogCreatedAt(filterStorefrontProducts(products))
}

/** Product detail lookup that hides non-test products while payment test mode is on. */
export function getStorefrontProduct(slug: string): Product | undefined {
  if (!isStorefrontProductVisible(slug)) return undefined
  return getProduct(slug)
}

export function getRelatedProducts(slug: string, limit = 3): Product[] {
  const current = getStorefrontProduct(slug) ?? getProduct(slug)
  if (!current) return getStorefrontProducts().slice(0, limit)
  return getStorefrontProducts()
    .filter((p) => p.slug !== slug && p.collections.some((c) => current.collections.includes(c)))
    .slice(0, limit)
}

export const categories = categoryNames

export function formatINR(value: number): string {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 0,
  }).format(value)
}
